In [1]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.feature_extraction.text import TfidfVectorizer
import pandas as pd

In [2]:
sentence1 = "they placed an order for 500 airbus aircraft."
sentence2 = "they will place an order for 500 boeing aircraft."

vectorizer = CountVectorizer().fit_transform(([sentence1,sentence2]))
vectors = vectorizer.toarray()

cosine_sim = cosine_similarity([vectors[0]],[vectors[1]])[0,0]

print("Cosine Similarity: ",cosine_sim)

Cosine Similarity:  0.7071067811865475

In [3]:
data = pd.read_csv("/Users/sevketugurel/Desktop/CosineSimilarity/IMDB.csv")
df = data.copy()
df = df.dropna(subset=["overview"]) # data değeri Nan olan satırları temizliyoruz

tfidf_vectorizer = TfidfVectorizer(stop_words="english")
tfidf_matrix = tfidf_vectorizer.fit_transform(df["overview"])
cosine_sim = cosine_similarity(tfidf_matrix,tfidf_matrix)
titles = df["title"].tolist()
long_data = []

for i in range(len(titles)):
    for j in range(i+1,len(titles)):
        title1 = titles[i]
        title2 = titles[j]
        score = cosine_sim[i,j]
        long_data.append([title1,title2,score])
long_df = pd.DataFrame(long_data,columns=["title1","title2","score"])
long_df = long_df[long_df["title1"] != long_df["title2"]]
long_df = long_df.sort_values(by="score",ascending=False)
long_df = pd.DataFrame(long_df)
long_df.head(10)

,title1,title2,score
17957278,Loro 2,Loro 1,1.000000
8119977,One Cut of the Dead,Final Cut,0.681184
31462848,Leroy & Stitch,Stitch! The Movie,0.624644
16966458,The Many Adventures of Winnie the Pooh,Winnie the Pooh,0.557787
11075980,"Batman: The Long Halloween, Part One","Batman: The Long Halloween, Part Two",0.550686
3628868,Toy Story,Toy Story 3,0.532348
16380605,Frozen II,Olaf's Frozen Adventure,0.530908
11476524,Mr. Deeds Goes to Town,Mr. Deeds,0.528573
2842879,How to Train Your Dragon: Homecoming,How to Train Your Dragon 2,0.521914
19565188,Pooh's Grand Adventure: The Search for Christo...,Winnie the Pooh,0.521618

In [4]:
my_list = long_df[long_df['title1'] == 'Frozen II']
my_list.head(10)

             title1                    title2     score
16380605  Frozen II   Olaf's Frozen Adventure  0.530908
16378990  Frozen II              Frozen Fever  0.419264
16377398  Frozen II                    Frozen  0.327509
16378635  Frozen II       Once Upon a Snowman  0.189971
16383677  Frozen II             The Counselor  0.162142
16383443  Frozen II               The Monster  0.139544
16378757  Frozen II  The Corpse of Anna Fritz  0.134648
16381212  Frozen II           Shrek the Third  0.122437
16378767  Frozen II                 Leap Year  0.121003
16379318  Frozen II         Anna and the King  0.114614

In [5]:
overview = df[df["title"] == "Frozen II"]["overview"].values[0]
print("Loro 2: ",overview)
overview2 = df[df["title"]=="Olaf's Frozen Adventure"]["overview"].values[0]
print("Gabriel: ",overview2)

Loro 2:  Elsa, Anna, Kristoff and Olaf head far into the forest to learn the truth about an ancient mystery of their kingdom.
Gabriel:  Olaf is on a mission to harness the best holiday traditions for Anna, Elsa, and Kristoff.